// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://app.forhims.com/?ref=godly
// Generated: 2026-06-04T15:37:20.095Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary';
export type ColorHex  = '#000000' | '#ffffff' | '#f0f0f0' | '#5d48db';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'sofia' | 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '500' | '400';

export type SpacingToken = '2px' | '60px' | '80px' | '100px' | '120px' | '133px' | '178px' | '210px' | '234px' | '285px' | '320px' | '360px' | '390px' | '428px' | '475px';

export type RadiusToken = '20px' | '27px' | '45px' | '52px' | '100px';

export type DurationToken = '200ms' | '600ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
