// Framer Motion presets — generated by designlang (motionlang)
// Source: https://app.forhims.com/?ref=godly
// 2026-06-04T15:37:20.097Z
//
//   import { transitions, variants } from './app.forhims.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.19, 1, 0.22, 1], // 3× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  sm: 0.2,
  lg: 0.6,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.6, ease: easings.easeOut },
  fast:  { duration: 0.300, ease: easings.easeOut },
  slow:  { duration: 1.080, ease: easings.easeOut },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.150 } },
  },
};

export default { easings, durations, transitions, variants };
