// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://cruisenow.ai
// Generated: 2026-06-03T18:26:00.229Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#1e1e2e' | '#f4f5f7' | '#ffffff' | '#2251f9' | '#4d4f5c' | '#2b2e3b' | '#0f1728' | '#2e90fa' | '#9d76ed' | '#edaafc' | '#518bff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'TT Interfaces Medium' | 'Times' | 'TT Interfaces Regular' | 'Cirka Variable' | 'TT Interfaces' | 'Cirka Bold' | 'Inter';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '300' | '600';

export type SpacingToken = '1px' | '4px' | '27px' | '32px' | '36px' | '46px' | '50px' | '64px' | '72px' | '80px' | '87px' | '120px' | '140px';

export type RadiusToken = '4px' | '8px' | '16px' | '24px' | '40px' | '100px' | '200px';

export type DurationToken = never;
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
