// Framer Motion presets — generated by designlang (motionlang)
// Source: https://cruisenow.ai
// 2026-06-03T18:26:00.230Z
//
//   import { transitions, variants } from './cruisenow.ai-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  standard: [0.25, 1, 0.5, 1],
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  fast: 0.15,
  base: 0.3,
  slow: 0.5,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.3, ease: easings.standard },
  fast:  { duration: 0.150, ease: easings.standard },
  slow:  { duration: 0.540, ease: easings.standard },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.075 } },
  },
};

export default { easings, durations, transitions, variants };
